#!/usr/bin/env bash

jekyll build

if [ $? -ne 0 ]; then
  echo "Jekyll build failed!"
  exit 1
fi

mkdir /tmp/jekyll
rm -rf /tmp/jekyll/*
cp -R ./_site/* /tmp/jekyll
git checkout master

if [ $? -ne 0 ]; then
  echo "Unable to checkout master! Do you have uncommited changes?"
  rm -rf /tmp/jekyll
  exit 1
fi

rm -rf ./*
cp -R /tmp/jekyll/* ./
git add -A .
git commit -m "Site published on $(date)"
git push origin master
git checkout source
git push origin source
git clean -f -d
rm -rf /tmp/jekyll
echo "Site published successfully."
